package shiroha:flow@0.2.0;

interface store {
  get: func(namespace: string, key: string) -> option<list<u8>>;
  put: func(namespace: string, key: string, value: list<u8>);
  delete: func(namespace: string, key: string) -> bool;
  list-keys: func(namespace: string, prefix: option<string>, limit: option<u32>) -> list<string>;
}
